<?php

namespace App\Observers;

use App\Models\Repository;
use Illuminate\Support\Facades\Http;

class RepositoryObserver
{
    public function CreateRepository(array $data, String $token)
    {
        $response = Http::withHeaders([
                    "Authorization" => $token,
                ])->withBody(
                    json_encode($data),
                    'application/json'
                )->post('https://api.github.com/user/repos');
        return $response;
    }

    public function CreateFile(array $data, String $url, String $token)
    {
        $response = Http::withHeaders([
                    "Authorization" => $token,
                ])->withBody(
                    json_encode($data),
                    'application/json'
                )->put($url);
        return $response;
    }
    
    /**
     * Handle the Repository "created" event.
     *
     * @param  \App\Models\Repository  $repository
     * @return void
     */
    public function created(Repository $repository)
    {
        $data = [
            "name" => $repository->name,
            "auto_init" => false,
            "private" => true
        ];

        $token = $repository->personal_access_token;

        // Create repositry via GitHub
        $response = json_decode($this->CreateRepository($data, $token)->body());

        // Confirm pathing
        $targetRepository = Repository::find($repository->id);
        $targetRepository->path = $response->full_name;
        $targetRepository->saveQuietly();
        

        $readMeContents = '# ' . $repository->name . '

Component library generated by Siteplot
    
Repo Created with the following settings:
```
name: ' . $repository->name . '
path: ' . $targetRepository->path . '
personal_access_token: *******************' . substr($token, -4) . '
```

All supporting components can be found in the ```/components``` folder
This component library can be mounted in any custom project via a [submodule](https://git-scm.com/book/en/v2/Git-Tools-Submodules)
';
        

        // Initialize ReadME.md
        $data = [
            "message" => "Creating Repository",
            "committer" => [
                "name" => "Siteplot Bot",
                "email" => "s.mark.toms+siteplot@gmail.com"
            ],
            "content" => base64_encode($readMeContents)
        ];

        $url = 'https://api.github.com/repos/' . $targetRepository->path . '/contents/README.md';

        $this->CreateFile($data, $url, $token);
    }

    /**
     * Handle the Repository "updated" event.
     *
     * @param  \App\Models\Repository  $repository
     * @return void
     */
    public function updated(Repository $repository)
    {
        //
    }

    /**
     * Handle the Repository "deleted" event.
     *
     * @param  \App\Models\Repository  $repository
     * @return void
     */
    public function deleted(Repository $repository)
    {
        //
    }

    /**
     * Handle the Repository "restored" event.
     *
     * @param  \App\Models\Repository  $repository
     * @return void
     */
    public function restored(Repository $repository)
    {
        //
    }

    /**
     * Handle the Repository "force deleted" event.
     *
     * @param  \App\Models\Repository  $repository
     * @return void
     */
    public function forceDeleted(Repository $repository)
    {
        //
    }
}
